# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ccf0e95b93e742698a4e3fcd0ac2907d71034af871ea543434b09555ed8108011b77721961500fab5b7fb063f6eaef111f4a6d46ca36344fd0700a25709c8f

test:
  secret_key_base: 6d04da4e587635c320eba1a64eb18b8dc92d69cbfea86d38955d978b19ecf1a1dc7ee0bc16a48f2df851d6f8f944c6325b0e759139fa365b15abb0715a8f4f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
